version: '3.0'

services:
  db:
    image: timescaledev/promscale-extension:0.1.2-ts2-pg12
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: timescale

  prometheus1:
    image: prom/prometheus:v2.26.0
    ports:
      - 9091:9090/tcp
    volumes:
      - ./prometheus1.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yaml:/etc/prometheus/prometheus.rules.yaml

  prometheus2:
    image: prom/prometheus:v2.26.0
    ports:
      - 9092:9090/tcp
    volumes:
      - ./prometheus2.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yaml:/etc/prometheus/prometheus.rules.yaml

  promscale1:
    image: timescale/promscale:0.3.0
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus1
    env_file:
      - promscale-compose.env

  promscale2:
    image: timescale/promscale:0.3.0
    ports:
      - 9202:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus2
    env_file:
      - promscale-compose.env

  grafana:
    image: grafana/grafana:7.3.1
    restart: always
    init: true
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/custom.ini:/etc/grafana/grafana.ini

  app:
    build:
      context: ./app
    ports:
      - 8080:8080/tcp
