version: '3.0'

services:
  db:
    image: timescaledev/promscale-extension:0.1.2-ts2-pg12
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: timescale

  prometheus1:
    image: prom/prometheus:v2.26.0
    ports:
      - 9091:9090/tcp
    volumes:
      - ./prometheus1.yaml:/etc/prometheus/prometheus.yml

  prometheus2:
    image: prom/prometheus:v2.26.0
    ports:
      - 9092:9090/tcp
    volumes:
      - ./prometheus2.yaml:/etc/prometheus/prometheus.yml

  promscale1:
    image: timescale/promscale:0.3.0
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus1
    env_file:
      - promscale-compose.env

  promscale2:
    image: timescale/promscale:0.3.0
    ports:
      - 9202:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus2
    env_file:
      - promscale-compose.env

  app:
    image: app
    build:
      context: ./app
    ports:
      - 3000:3000/tcp
