global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    __replica__: prometheus1
    cluster: cluster1

rule_files:
  - prometheus.rules.yaml

remote_write:
  - url: http://promscale1:9201/write
    remote_timeout: 30s
    queue_config:
      batch_send_deadline: 10s
      capacity: 10000
      max_backoff: 10s
      max_samples_per_send: 3000
      max_shards: 200
      min_backoff: 100ms
      min_shards: 4
remote_read:
  - url: http://promscale1:9201/read
    read_recent: true

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
        - app:8080
