global:
  scrape_interval:     15s
  evaluation_interval: 15s

remote_write:
  - url: http://promscale1:9201/write
remote_read:
  - url: http://promscale1:9201/read
    read_recent: true

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
        - app:3000
