apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: db:5432
    access: proxy
    database: timescale
    user: postgres
    basicAuth: false
    isDefault: true
    secureJsonData:
      password: "postgres"
    jsonData:
      editable: true
      version: 1
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1206 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
